#!/bin/sh
# Updates the project from eclipse workspace

make clean
rm -rf ./include/*

cp -R ~/Dropbox/programming/cpp/qpp_xcode/qpp/example.cpp ./
cp -R ~/Dropbox/programming/cpp/qpp_xcode/qpp/include/* ./include

make
