#!/bin/sh
# Updates the project from eclipse workspace

make clean
rm -rf ./src/*
rm -rf ./include/*

cp ~/Dropbox/programming/workspace/quantum++/src/* ./src
cp ~/Dropbox/programming/workspace/quantum++/include/* ./include

#make
