from __future__ import annotations
from pyqpp._pyqpp import BitCircuit
from pyqpp._pyqpp import CondWhile
from pyqpp._pyqpp import DynamicBitset
from pyqpp._pyqpp import QCircuit
from pyqpp._pyqpp import QDensityDummyEngine
from pyqpp._pyqpp import QDensityEngine
from pyqpp._pyqpp import QDensityNoisyEngine
from pyqpp._pyqpp import QFT
from pyqpp._pyqpp import QKetDummyEngine
from pyqpp._pyqpp import QKetEngine
from pyqpp._pyqpp import QKetEngine as QEngine
from pyqpp._pyqpp import QKetNoisyEngine as QNoisyEngine
from pyqpp._pyqpp import QKetNoisyEngine
from pyqpp._pyqpp import QubitAmplitudeDampingNoise
from pyqpp._pyqpp import QubitBitFlipNoise
from pyqpp._pyqpp import QubitBitPhaseFlipNoise
from pyqpp._pyqpp import QubitDepolarizingNoise
from pyqpp._pyqpp import QubitPhaseDampingNoise
from pyqpp._pyqpp import QubitPhaseFlipNoise
from pyqpp._pyqpp import QuditDepolarizingNoise
from pyqpp._pyqpp import TFQ
from pyqpp._pyqpp import absm
from pyqpp._pyqpp import abssq
from pyqpp._pyqpp import adjoint
from pyqpp._pyqpp import anticomm
from pyqpp._pyqpp import apply
from pyqpp._pyqpp import applyCTRL
from pyqpp._pyqpp import applyCTRL_fan
from pyqpp._pyqpp import applyQFT
from pyqpp._pyqpp import applyTFQ
from pyqpp._pyqpp import avg
from pyqpp._pyqpp import bernoulli
from pyqpp._pyqpp import bloch2rho
from pyqpp._pyqpp import choi2kraus
from pyqpp._pyqpp import choi2super
from pyqpp._pyqpp import comm
from pyqpp._pyqpp import complement
from pyqpp._pyqpp import compose_CTRL_circuit
from pyqpp._pyqpp import compose_circuit
from pyqpp._pyqpp import compperm
from pyqpp._pyqpp import concurrence
from pyqpp._pyqpp import conjugate
from pyqpp._pyqpp import const_proxy_to_engine_dits
from pyqpp._pyqpp import contfrac2x
from pyqpp._pyqpp import convergents
from pyqpp._pyqpp import cor
from pyqpp._pyqpp import cosm
from pyqpp._pyqpp import couple_circuit_left
from pyqpp._pyqpp import couple_circuit_right
from pyqpp._pyqpp import cov
from pyqpp._pyqpp import det
from pyqpp._pyqpp import dirac
from pyqpp._pyqpp import dirac_t
from pyqpp._pyqpp import dirsum
from pyqpp._pyqpp import dirsumpow
from pyqpp._pyqpp import discard
from pyqpp._pyqpp import egcd
from pyqpp._pyqpp import eig
from pyqpp._pyqpp import entanglement
from pyqpp._pyqpp import entropy
from pyqpp._pyqpp import evals
from pyqpp._pyqpp import evects
from pyqpp._pyqpp import expm
from pyqpp._pyqpp import factors
from pyqpp._pyqpp import funm
from pyqpp._pyqpp import gates
from pyqpp._pyqpp import gcd
from pyqpp._pyqpp import gconcurrence
from pyqpp._pyqpp import grams
from pyqpp._pyqpp import hash_eigen
from pyqpp._pyqpp import heig
from pyqpp._pyqpp import hevals
from pyqpp._pyqpp import hevects
from pyqpp._pyqpp import inverse
from pyqpp._pyqpp import invperm
from pyqpp._pyqpp import ip
from pyqpp._pyqpp import isprime
from pyqpp._pyqpp import kraus2choi
from pyqpp._pyqpp import kraus2super
from pyqpp._pyqpp import kron
from pyqpp._pyqpp import kronpow
from pyqpp._pyqpp import lcm
from pyqpp._pyqpp import load_cmat
from pyqpp._pyqpp import load_rmat
from pyqpp._pyqpp import logdet
from pyqpp._pyqpp import logm
from pyqpp._pyqpp import lognegativity
from pyqpp._pyqpp import marginalX
from pyqpp._pyqpp import marginalY
from pyqpp._pyqpp import measure
from pyqpp._pyqpp import measure_seq
from pyqpp._pyqpp import mket
from pyqpp._pyqpp import modinv
from pyqpp._pyqpp import modmul
from pyqpp._pyqpp import modpow
from pyqpp._pyqpp import mprj
from pyqpp._pyqpp import multiidx2n
from pyqpp._pyqpp import n2multiidx
from pyqpp._pyqpp import negativity
from pyqpp._pyqpp import norm
from pyqpp._pyqpp import normalize
from pyqpp._pyqpp import omega
from pyqpp._pyqpp import powm
from pyqpp._pyqpp import prj
from pyqpp._pyqpp import prod
from pyqpp._pyqpp import proxy_to_engine_dits
from pyqpp._pyqpp import ptrace
from pyqpp._pyqpp import ptrace1
from pyqpp._pyqpp import ptrace2
from pyqpp._pyqpp import ptranspose
from pyqpp._pyqpp import qRAM
from pyqpp._pyqpp import qasm
from pyqpp._pyqpp import qmutualinfo
from pyqpp._pyqpp import qpe_circuit
from pyqpp._pyqpp import rand
from pyqpp._pyqpp import randH
from pyqpp._pyqpp import randU
from pyqpp._pyqpp import randV
from pyqpp._pyqpp import randidx
from pyqpp._pyqpp import randket
from pyqpp._pyqpp import randkraus
from pyqpp._pyqpp import randn
from pyqpp._pyqpp import random_circuit_count
from pyqpp._pyqpp import random_circuit_depth
from pyqpp._pyqpp import randperm
from pyqpp._pyqpp import randprime
from pyqpp._pyqpp import randprob
from pyqpp._pyqpp import randrho
from pyqpp._pyqpp import renyi
from pyqpp._pyqpp import replicate
from pyqpp._pyqpp import reset
from pyqpp._pyqpp import reshape
from pyqpp._pyqpp import rho2bloch
from pyqpp._pyqpp import rho2pure
from pyqpp._pyqpp import sample
from pyqpp._pyqpp import save
from pyqpp._pyqpp import schatten
from pyqpp._pyqpp import schmidt
from pyqpp._pyqpp import schmidtA
from pyqpp._pyqpp import schmidtB
from pyqpp._pyqpp import schmidtcoeffs
from pyqpp._pyqpp import schmidtprobs
from pyqpp._pyqpp import set_prng_seed
from pyqpp._pyqpp import sigma
from pyqpp._pyqpp import sinm
from pyqpp._pyqpp import spectralpowm
from pyqpp._pyqpp import sqrtm
from pyqpp._pyqpp import states
from pyqpp._pyqpp import sum
from pyqpp._pyqpp import super2choi
from pyqpp._pyqpp import super2kraus
from pyqpp._pyqpp import svals
from pyqpp._pyqpp import svd
from pyqpp._pyqpp import svdU
from pyqpp._pyqpp import svdV
from pyqpp._pyqpp import syspermute
from pyqpp._pyqpp import trace
from pyqpp._pyqpp import transpose
from pyqpp._pyqpp import tsallis
from pyqpp._pyqpp import uniform
from pyqpp._pyqpp import var
from pyqpp._pyqpp import x2contfrac
from pyqpp._pyqpp import zket2dits
from . import _pyqpp
__all__: list = ['BitCircuit', 'CondWhile', 'DynamicBitset', 'QCircuit', 'QDensityDummyEngine', 'QDensityEngine', 'QDensityNoisyEngine', 'QEngine', 'QFT', 'QKetDummyEngine', 'QKetEngine', 'QKetNoisyEngine', 'QNoisyEngine', 'QPP_VERSION_NUM', 'QPP_VERSION_STR', 'QubitAmplitudeDampingNoise', 'QubitBitFlipNoise', 'QubitBitPhaseFlipNoise', 'QubitDepolarizingNoise', 'QubitPhaseDampingNoise', 'QubitPhaseFlipNoise', 'QuditDepolarizingNoise', 'TFQ', 'absm', 'abssq', 'adjoint', 'anticomm', 'apply', 'applyCTRL', 'applyCTRL_fan', 'applyQFT', 'applyTFQ', 'avg', 'bernoulli', 'bloch2rho', 'choi2kraus', 'choi2super', 'comm', 'complement', 'compose_CTRL_circuit', 'compose_circuit', 'compperm', 'concurrence', 'conjugate', 'const_proxy_to_engine_dits', 'contfrac2x', 'convergents', 'cor', 'cosm', 'couple_circuit_left', 'couple_circuit_right', 'cov', 'det', 'dirac', 'dirac_t', 'dirsum', 'dirsumpow', 'discard', 'ee', 'egcd', 'eig', 'entanglement', 'entropy', 'evals', 'evects', 'expm', 'factors', 'funm', 'gates', 'gcd', 'gconcurrence', 'grams', 'hash_eigen', 'heig', 'hevals', 'hevects', 'infty', 'inverse', 'invperm', 'ip', 'isprime', 'kraus2choi', 'kraus2super', 'kron', 'kronpow', 'lcm', 'load_cmat', 'load_rmat', 'logdet', 'logm', 'lognegativity', 'marginalX', 'marginalY', 'measure', 'measure_seq', 'mket', 'modinv', 'modmul', 'modpow', 'mprj', 'multiidx2n', 'n2multiidx', 'negativity', 'norm', 'normalize', 'omega', 'pi', 'powm', 'prj', 'prod', 'proxy_to_engine_dits', 'ptrace', 'ptrace1', 'ptrace2', 'ptranspose', 'qRAM', 'qasm', 'qmutualinfo', 'qpe_circuit', 'rand', 'randH', 'randU', 'randV', 'randidx', 'randket', 'randkraus', 'randn', 'random_circuit_count', 'random_circuit_depth', 'randperm', 'randprime', 'randprob', 'randrho', 'renyi', 'replicate', 'reset', 'reshape', 'rho2bloch', 'rho2pure', 'sample', 'save', 'schatten', 'schmidt', 'schmidtA', 'schmidtB', 'schmidtcoeffs', 'schmidtprobs', 'set_prng_seed', 'sigma', 'sinm', 'spectralpowm', 'sqrtm', 'states', 'sum', 'super2choi', 'super2kraus', 'svals', 'svd', 'svdU', 'svdV', 'syspermute', 'trace', 'transpose', 'tsallis', 'uniform', 'var', 'x2contfrac', 'zket2dits', 'gates', 'states', 'qasm', '__version__', 'QPP_VERSION_STR', 'QPP_VERSION_NUM']
def _version_to_number(version: str) -> int:
    """
    
    Convert a semantic version string to a numeric value.
    
    Example:
        "7.0.0" -> 70000
        "7.1.3" -> 70103
    """
QPP_VERSION_NUM: int = 70001
QPP_VERSION_STR: str = '7.0.1'
__version__: str = '7.0.1'
_core_all: list = ['BitCircuit', 'CondWhile', 'DynamicBitset', 'QCircuit', 'QDensityDummyEngine', 'QDensityEngine', 'QDensityNoisyEngine', 'QEngine', 'QFT', 'QKetDummyEngine', 'QKetEngine', 'QKetNoisyEngine', 'QNoisyEngine', 'QPP_VERSION_NUM', 'QPP_VERSION_STR', 'QubitAmplitudeDampingNoise', 'QubitBitFlipNoise', 'QubitBitPhaseFlipNoise', 'QubitDepolarizingNoise', 'QubitPhaseDampingNoise', 'QubitPhaseFlipNoise', 'QuditDepolarizingNoise', 'TFQ', 'absm', 'abssq', 'adjoint', 'anticomm', 'apply', 'applyCTRL', 'applyCTRL_fan', 'applyQFT', 'applyTFQ', 'avg', 'bernoulli', 'bloch2rho', 'choi2kraus', 'choi2super', 'comm', 'complement', 'compose_CTRL_circuit', 'compose_circuit', 'compperm', 'concurrence', 'conjugate', 'const_proxy_to_engine_dits', 'contfrac2x', 'convergents', 'cor', 'cosm', 'couple_circuit_left', 'couple_circuit_right', 'cov', 'det', 'dirac', 'dirac_t', 'dirsum', 'dirsumpow', 'discard', 'ee', 'egcd', 'eig', 'entanglement', 'entropy', 'evals', 'evects', 'expm', 'factors', 'funm', 'gates', 'gcd', 'gconcurrence', 'grams', 'hash_eigen', 'heig', 'hevals', 'hevects', 'infty', 'inverse', 'invperm', 'ip', 'isprime', 'kraus2choi', 'kraus2super', 'kron', 'kronpow', 'lcm', 'load_cmat', 'load_rmat', 'logdet', 'logm', 'lognegativity', 'marginalX', 'marginalY', 'measure', 'measure_seq', 'mket', 'modinv', 'modmul', 'modpow', 'mprj', 'multiidx2n', 'n2multiidx', 'negativity', 'norm', 'normalize', 'omega', 'pi', 'powm', 'prj', 'prod', 'proxy_to_engine_dits', 'ptrace', 'ptrace1', 'ptrace2', 'ptranspose', 'qRAM', 'qasm', 'qmutualinfo', 'qpe_circuit', 'rand', 'randH', 'randU', 'randV', 'randidx', 'randket', 'randkraus', 'randn', 'random_circuit_count', 'random_circuit_depth', 'randperm', 'randprime', 'randprob', 'randrho', 'renyi', 'replicate', 'reset', 'reshape', 'rho2bloch', 'rho2pure', 'sample', 'save', 'schatten', 'schmidt', 'schmidtA', 'schmidtB', 'schmidtcoeffs', 'schmidtprobs', 'set_prng_seed', 'sigma', 'sinm', 'spectralpowm', 'sqrtm', 'states', 'sum', 'super2choi', 'super2kraus', 'svals', 'svd', 'svdU', 'svdV', 'syspermute', 'trace', 'transpose', 'tsallis', 'uniform', 'var', 'x2contfrac', 'zket2dits']
ee: float = 2.718281828459045
infty: float  # value = inf
pi: float = 3.141592653589793
