from __future__ import annotations
import numpy
import numpy.typing
import typing
__all__: list[str] = ['GHZ', 'W', 'b00', 'b01', 'b10', 'b11', 'j', 'jn', 'mes', 'minus', 'one', 'pGHZ', 'pW', 'pb00', 'pb01', 'pb10', 'pb11', 'plus', 'px0', 'px1', 'py0', 'py1', 'pz0', 'pz1', 'x0', 'x1', 'y0', 'y1', 'z0', 'z1', 'zero']
def j(j: typing.SupportsInt | typing.SupportsIndex, d: typing.SupportsInt | typing.SupportsIndex = 2) -> typing.Annotated[numpy.typing.NDArray[numpy.complex128], "[m, 1]"]:
    """
    $|j\\rangle$ computational basis state of a single qudit
    """
def jn(j: typing.SupportsInt | typing.SupportsIndex, n: typing.SupportsInt | typing.SupportsIndex = 1, d: typing.SupportsInt | typing.SupportsIndex = 2) -> typing.Annotated[numpy.typing.NDArray[numpy.complex128], "[m, 1]"]:
    """
    $|j\\rangle^{\\otimes n}$ state of n qudits
    """
def mes(d: typing.SupportsInt | typing.SupportsIndex = 2) -> typing.Annotated[numpy.typing.NDArray[numpy.complex128], "[m, 1]"]:
    """
    Maximally entangled state of 2 qudits
    """
def minus(n: typing.SupportsInt | typing.SupportsIndex = 1) -> typing.Annotated[numpy.typing.NDArray[numpy.complex128], "[m, 1]"]:
    """
    Minus state of n qubits
    """
def one(n: typing.SupportsInt | typing.SupportsIndex = 1, d: typing.SupportsInt | typing.SupportsIndex = 2) -> typing.Annotated[numpy.typing.NDArray[numpy.complex128], "[m, 1]"]:
    """
    One state of n qudits
    """
def plus(n: typing.SupportsInt | typing.SupportsIndex = 1) -> typing.Annotated[numpy.typing.NDArray[numpy.complex128], "[m, 1]"]:
    """
    Plus state of n qubits
    """
def zero(n: typing.SupportsInt | typing.SupportsIndex = 1, d: typing.SupportsInt | typing.SupportsIndex = 2) -> typing.Annotated[numpy.typing.NDArray[numpy.complex128], "[m, 1]"]:
    """
    Zero state of n qudits
    """
GHZ: numpy.ndarray  # value = array([[0.70710678+0.j],...
W: numpy.ndarray  # value = array([[0.        +0.j],...
b00: numpy.ndarray  # value = array([[0.70710678+0.j],...
b01: numpy.ndarray  # value = array([[0.        +0.j],...
b10: numpy.ndarray  # value = array([[ 0.70710678+0.j],...
b11: numpy.ndarray  # value = array([[ 0.        +0.j],...
pGHZ: numpy.ndarray  # value = array([[0.5+0.j, 0. +0.j, 0. +0.j, 0. +0.j, 0. +0.j, 0. +0.j, 0. +0.j,...
pW: numpy.ndarray  # value = array([[0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j,...
pb00: numpy.ndarray  # value = array([[0.5+0.j, 0. +0.j, 0. +0.j, 0.5+0.j],...
pb01: numpy.ndarray  # value = array([[0. +0.j, 0. +0.j, 0. +0.j, 0. +0.j],...
pb10: numpy.ndarray  # value = array([[ 0.5+0.j,  0. +0.j,  0. +0.j, -0.5+0.j],...
pb11: numpy.ndarray  # value = array([[ 0. +0.j,  0. +0.j,  0. +0.j,  0. +0.j],...
px0: numpy.ndarray  # value = array([[0.5+0.j, 0.5+0.j],...
px1: numpy.ndarray  # value = array([[ 0.5+0.j, -0.5+0.j],...
py0: numpy.ndarray  # value = array([[0.5+0.j , 0. -0.5j],...
py1: numpy.ndarray  # value = array([[0.5+0.j , 0. +0.5j],...
pz0: numpy.ndarray  # value = array([[1.+0.j, 0.+0.j],...
pz1: numpy.ndarray  # value = array([[0.+0.j, 0.+0.j],...
x0: numpy.ndarray  # value = array([[0.70710678+0.j],...
x1: numpy.ndarray  # value = array([[ 0.70710678+0.j],...
y0: numpy.ndarray  # value = array([[0.70710678+0.j        ],...
y1: numpy.ndarray  # value = array([[ 0.70710678+0.j        ],...
z0: numpy.ndarray  # value = array([[1.+0.j],...
z1: numpy.ndarray  # value = array([[0.+0.j],...
