# MATLAB support (disabled by default)
option(QPP_MATLAB "Enable MATLAB support" OFF)

if(${QPP_MATLAB})
  message(STATUS "Detecting MATLAB...")
  find_package(Matlab REQUIRED COMPONENTS MX_LIBRARY MAT_LIBRARY)
  if(MATLAB_FOUND)
    target_link_libraries(libqpp INTERFACE Matlab::mat Matlab::mx)
  endif()
endif()
