# MATLAB support, disabled by default
option(QPP_MATLAB "MATLAB support" OFF)
if(${QPP_MATLAB})
  message(STATUS "Detecting MATLAB...")
  find_package(Matlab REQUIRED COMPONENTS MX_LIBRARY MAT_LIBRARY)
  if(MATLAB_FOUND)
    include_directories(SYSTEM ${Matlab_INCLUDE_DIRS})
    set(QPP_MATLAB_LINK_DEPS Matlab::mat Matlab::mx)
    message(STATUS "Detected MATLAB in: ${Matlab_ROOT_DIR}")
  else()
    message(FATAL_ERROR "Could not detect MATLAB, aborting")
  endif()
endif()
